app/watlist/models/__init__.py
from .models import User,Movie

app/watlist/models/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from realproject import db
class User(db.Model,UserMixin):
    id = db.Column(db.Integer,primary_key=True) #主键
    name = db.Column(db.String(20)) #名字
    username = db.Column(db.String(20))
    password = db.Column(db.String(128))
    def set_password(self,password_hash):# 用来设置密码的方法，接受密码作为参数
        self.password = generate_password_hash(password_hash) # 将生成的密码保持到对应字段
    def validate_password(self,password_hash): # 用于验证密码的方法，接受密码作为参数
        return check_password_hash(self.password,password_hash)

class Movie(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(60)) #电影标题
    year = db.Column(db.String(4))   #电影年份

app/watlist/views/__init__.py
from .hello import bg #引入蓝图

app/watlist/views/hello.py
from flask import render_template, Blueprint, request, flash, redirect, url_for
import click
from app.watlist.models import User, Movie
from realproject import db
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from realproject import app

login_manage = LoginManager(app) #实例化扩展类
login_manage.login_view = 'watlist.login'
bg = Blueprint('watlist',__name__,url_prefix='/watlist',template_folder='../templates',static_folder='../static')

@login_manage.user_loader
def load_user(user_id):  # 创建用户加载回调函数，接受用户 ID 作为参数
    user = User.query.get(int(user_id)) #用 ID 作为 User 模型的主键查询对应的用户
    return user  #返回用户对象

@bg.cli.command() #注册成为命令
def forge():
    name = 'Kanding Mu'
    movies = [
        {'title': 'My Neighbor Totoro', 'year': '1988'},
        {'title': 'Dead Poets Society', 'year': '1989'},
        {'title': 'A Perfect World', 'year': '1993'},
        {'title': 'Leon', 'year': '1994'},
        {'title': 'Mahjong', 'year': '1996'},
        {'title': 'Swallowtail Butterfly', 'year': '1996'},
        {'title': 'King of Comedy', 'year': '1999'},
        {'title': 'Devils on the Doorstep', 'year': '1999'},
        {'title': 'WALL-E', 'year': '2008'},
        {'title': 'The Pork of Music', 'year': '2012'},
    ]
    user = User(name=name)
    db.session.add(user)
    for m in movies:
        movie = Movie(title=m['title'],year=m['year'])
        db.session.add(movie)
    db.session.commit()
    click.echo('Done...')

#生成管理员账户
@bg.cli.command()
@click.option('--username', prompt=True, help='The username used to login.')
@click.option('--password', prompt=True, hide_input=True, confirmation_prompt=True, help='The password used to login.')
def admin(username,password):
    db.create_all()
    user = User.query.first()
    if user is not None:
        click.echo('updating user...')
        user.username = username
        user.set_password(password) #设置密码
    else:
        click.echo('Creating user...')
        user = User(username=username,name="Admin")
        user.set_password(password)
        db.session.add(user)
    db.session.commit()
    click.echo('Done')

@bg.route('/login',methods=['GET','POST'])
def login():
    if request.method=='POST':
        username = request.form['username']
        password = request.form['password']
        if not username or not password:
            flash('Invald input...')
            return redirect(url_for('watlist.login'))
        user = User.query.first()
        if username == user.username and user.validate_password(password):
            login_user(user)
            flash('Login success...')
            return redirect(url_for('watlist.index'))
        flash('Invalid username or password...')
        return redirect(url_for('watlist.login'))
    return render_template('login.html')

@bg.route('/settings',methods=['GET','POST'])
@login_required
def settings():
    if request.method=='POST':
        name = request.form['name']
        if not name or len(name) > 20:
            flash('Invalid input...')
            return redirect(url_for('watlist.settings'))
        current_user.name = name
        db.session.commit()
        return redirect(url_for('watlist.index'))
    return render_template('settings.html')

@bg.route('/logout')
@login_required
def logout():
    logout_user() #登出用户
    flash('Goodbye...')
    return redirect(url_for('watlist.index'))

@bg.context_processor #上下文处理函数
def inject_user():
    user = User.query.first()
    return dict(user=user)

@bg.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'),404

@bg.route('/')
def index():
    #user = User.query.first() #读取用用户记录
    movies = Movie.query.all() #读取所有电影记录
    return render_template('index.html', movies=movies)

@bg.route('/movie/add',methods=['GET','POST'])
@login_required
def create():
    if request.method == 'POST':
        title = request.form.get('title')
        year = request.form.get('year')
        if not title or not year or len(year) > 4 or len(title) > 60:
            flash('Invalid input...')
            return redirect(url_for('watlist.create'))
        movie = Movie(title=title,year=year)
        db.session.add(movie)
        db.session.commit()
        flash('Item created success...')
        return redirect(url_for('watlist.index'))
    movies = Movie.query.all()
    return render_template('create.html',movies=movies)

@bg.route('/movie/edit/<int:movie_id>',methods=['GET','POST'])
@login_required
def edit(movie_id):
    movie = Movie.query.get_or_404(movie_id)
    if request.method == 'POST':
        title = request.form['title']
        year = request.form['year']
        if not title or not year or len(year) !=4 or len(title) > 60:
            flash('Invalid input...')
            return redirect(url_for('edit',movie_id=movie_id)) #重定向回对应的编辑页面
        movie.title=title #更新标题
        movie.year=year   #更新年份
        db.session.commit()
        flash('Item update success...')
        return redirect(url_for('watlist.index'))#重定向到主页
    return render_template('edit.html',movie=movie)

@bg.route('/movie/delete/<int:movie_id>',methods=['POST'])
@login_required
def delete(movie_id):
    movie = Movie.query.get_or_404(movie_id)
    db.session.delete(movie)
    db.session.commit()
    flash('Item deleted...')
    return redirect(url_for('watlist.index'))

realproject/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from realproject.settings import BASE_DIR

app = Flask(__name__, instance_relative_config=True)
db = SQLAlchemy()

def create_app(test_config=None):

    if test_config is None:
        CONFIG_DIR = BASE_DIR / 'realproject/settings.py'
        app.config.from_pyfile(CONFIG_DIR,silent=True)
    else:
        app.config.from_mapping(test_config)
    #绑定数据库
    db.init_app(app)

    #注册migrate
    #递归创建目录，确保项目文件存在
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass
    # 注册视图
    register_bg(app)

    return app

def register_bg(app:Flask):
    """注册视图方法"""
    from app.watlist import views as watlist
    from app.watlist import models
    #注册蓝图
    app.register_blueprint(watlist.bg)

    #首页url
    #app.add_url_rule(rule='/',endpoint='index',view_func=watlist.hello.index)

app/watlist/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="utf-8">
        <!--meta这个元素会设置页面的视口，让页面根据设备的宽度来自动缩放页面，这样会让移动设备拥有更好的浏览体验：-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- 插入到页面标题上方 -->
    {% for message in get_flashed_messages() %}
         <div class="alert">{{ message }}</div>
    {% endfor %}

    <title>{{ user.name }}'s Watchlist</title>
    <link rel="stylesheet" href="{{ url_for('watlist.static', filename='css/style.css') }}" type="text/css">
    {% endblock %}

</head>
<body>

    <h2>
        <img alt="Avatar" class="avatar" src="{{ url_for('watlist.static', filename='images/avatar.png') }}">
        {{ user.name }}'s Watchlist
    </h2>
    <nav>
        <ul>
            {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('watlist.settings') }}">Settings</a></li>
                <li><a href="{{ url_for('watlist.logout') }}">Logout</a></li>
            {% else %}
                 <li><a href="{{ url_for('watlist.login') }}">Login</a></li>
            {% endif %}
             <li><a href="{{ url_for('watlist.index') }}">Home</a></li>
        </ul>
    </nav>
    {% block content %}
        <span class="float-right">
                <a class="imdb" href="https://www.imdb.com/find?q={{ movie.title }}" target="_blank" title="Find this movie on IMDb">IMDb</a>
        </span>
    {% endblock %}
    <footer>
        <img alt="Walking Totoro" class="totoro" src="{{ url_for('watlist.static', filename='images/totoro.png') }}">
        <small>&copy; 2023 <a href="http://helloflask.com/book/3">HelloFlask</a></small>
    </footer>
</body>
</html>

app/watlist/templates/create.html
{% extends 'base.html' %}
{% block content %}
<p>{{ movies|length }} Titles</p>
<form method="post">
    Name <input type="text" name="title" autocomplete="off" required>
    Year <input type="text" name="year" autocomplete="off" required>
    <input class="btn" type="submit" name="submit" value="Add">
</form>
{% endblock %}

app/watlist/templates/edit.html
{% extends 'base.html'%}

{% block content %}
    <h3>Edit Item</h3>
    <form method="post">
        Name = <input type="text" name="title" autocomplete="off" required value="{{ movie.title }}">
        Name = <input type="text" name="year" autocomplete="off" required value="{{ movie.year }}">
        <input class="btn" type="submit" name="submit" value="Update">
    </form>
{% endblock %}

app/watlist/templates/index.html
{% extends 'base.html' %}
    {% block content %}
        <!-- 在模板中可以直接使用 current_user 变量 -->

    {# 使用 length 过滤器获取 movies 变量的长度 #}
    <p>{{ movies|length }} Titles
         {% if current_user.is_authenticated %}
            <a class="btn" href="{{ url_for('watlist.create') }}">Add</a>
         {% endif %}
    </p>

    <ul class="movie-list">
        {% for movie in movies %}  {# 迭代 movies 变量 #}
        <li>{{ movie.title }} - {{ movie.year }}
            {% if current_user.is_authenticated %}
                <span class="float-right">
                    <a class="btn" href="{{ url_for('watlist.edit', movie_id=movie.id) }}">Edit</a>
                </span>
            {% endif %}

            {% if current_user.is_authenticated %}
                <span class="float-right">
                    <form class="inline-form" method="post" action="{{ url_for('watlist.delete', movie_id=movie.id) }}">
                        <input class="btn" type="submit" name="delete" value="Delete" onclick="return confirm('Are you sure?')">
                    </form>
                </span>
            {% endif %}

            <span class="float-right">
                <a class="imdb" href="https://www.imdb.com/find?q={{ movie.title }}" target="_blank" title="Find this movie on IMDb">IMDb</a>
            </span>
        </li>  {# 等同于 movie['title'] #}
        {% endfor %}  {# 使用 endfor 标签结束 for 语句 #}
    </ul>
    {% endblock %}

app/watlist/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h3>Login</h3>
    <form method="post">
        Username<br>
        <input type="text" name="username" required><br><br>
        Password<br>
        <!-- 密码输入框的 type 属性使用 password，会将输入值显示为圆点 -->
        <input type="password" name="password" required><br><br>
        <input class="btn" type="submit" name="submit" value="Submit">
    </form>
{% endblock %}

app/watlist/templates/settings.html
{% extends 'base.html' %}
{% block content %}
    <h3>Settings</h3>
    <form method="post">
    Your Name <input type="text" name="name" autocomplete="off" required value="{{ current_user.name }}">
    <input class="btn" type="submit" name="submit" value="Save">
    </form>
{% endblock %}